[theme]
primaryColor = "#0077B6"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E2130"
textColor = "#FAFAFA"
font = "sans serif"

[server]
maxUploadSize = 5
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false
